"""added about_me and last_seen in User

Revision ID: 2dc675bc3ebc
Revises: 22a86827065b
Create Date: 2013-09-22 22:24:51.554402

"""

# revision identifiers, used by Alembic.
revision = '2dc675bc3ebc'
down_revision = '22a86827065b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    ### end Alembic commands ###
